### ISSUE TITLE
Add minimum documentation

### ISSUE THREAD

**Issue by lrapetti** [ami-iit/biomechanical-analysis-framework#1]
Basic documentation include:
- [ ] `README.md`
- [x] `CHANGELOG.md`
- [x] `.gitignore`

**Comment by claudia-lat** [comment]
@davidegorbani is there the missing part of the documentation in BAF? If yes, feel free to close this issue

**Comment by davidegorbani** [comment]
Not yet, I still have to write it.

**Comment by davidegorbani** [comment]
I opened #38 to address this issue.
