### ISSUE TITLE
Add gravity and floor contact task to HumanIK

### ISSUE THREAD

**Issue by davidegorbani** [ami-iit/biomechanical-analysis-framework#20]
After having added the orientation task in `HumanIK`, I open this issue to add also the gravity task to the class. The idea is to import the [gravityTask](https://github.com/ami-iit/bipedal-locomotion-framework/blob/master/src/IK/include/BipedalLocomotion/IK/GravityTask.h) implemented in `blf`.

CC @traversaro @GiulioRomualdi

**Comment by davidegorbani** [comment]
I created the branch [add_gravity_task](https://github.com/ami-iit/biomechanical-analysis-framework/tree/add_gravity_task) to address this issue.

**Comment by davidegorbani** [comment]
Looking at the configuration file for the IK of HDE, I noticed that there is also another task which is used named `floorContact`.
I had a look at the code in HDE and I found out that this is a position task:

https://github.com/robotology/human-dynamics-estimation/blob/b5c6e44d2e0065ab88b5cc057ea1608ed2ac337e/devices/HumanStateProvider/HumanStateProvider.cpp#L2569-L2576

and this task is used to set the position of the foot when it is in contact with the ground and allows the estimation of the base position, but it is not clear to me which position is set as the target.

**Comment by davidegorbani** [comment]
I found [here](https://github.com/robotology/human-dynamics-estimation/blob/b5c6e44d2e0065ab88b5cc057ea1608ed2ac337e/devices/HumanStateProvider/HumanStateProvider.cpp#L1852-L1863) how is set the position of the foot in contact; as we also discussed with @GiulioRomualdi, it is set using the legged odometry at the instant in which the foot touches the ground.

**Comment by davidegorbani** [comment]
I added the two tasks and compared the base pose estimation of the `HumanIK` and the HDE IK; the red model is the one obtained with the HDE IK while the other one is obtained with `HumanIK`.

[Screencast from 29-02-2024 09-03-27.webm](https://github.com/ami-iit/biomechanical-analysis-framework/assets/101326942/fec2491a-5f8c-4f34-8447-1bf86237575b)

In this case, I used a `SO3Task` for the right and left feet in the `HumanIK` IK while in the HDE IK a gravity task is used for those two frames. If a use a `GravityTask` for the feet, then they are free to rotate along the `z` axis and the estimation is worse, as it is possible to notice from the following video.

[Screencast from 29-02-2024 09-21-39.webm](https://github.com/ami-iit/biomechanical-analysis-framework/assets/101326942/0ab3506c-8dc1-4af5-9614-32f8badcbb56)

**Comment by GiulioRomualdi** [comment]
Well done!

**Comment by davidegorbani** [comment]
> If a use a `GravityTask` for the feet, then they are free to rotate along the `z` axis and the estimation is worse, as it is possible to notice from the following video.

The reason for this behaviour is probably due to the fact that in `HumanIK` there is not a regularization term, as suggested by @traversaro. I will add it to the class and repeat the same test.

**Comment by davidegorbani** [comment]
I also noticed that the IK in HDE also allows for setting constraints on the joints position; I opened #22 to address this issue.
