### ISSUE TITLE
Remove YarpImplementation from Logging

### ISSUE THREAD

**Issue by davidegorbani** [ami-iit/biomechanical-analysis-framework#44]
Since we want to move away from `YARP`, does it make sense to remove the [`YarpImplementation`](https://github.com/ami-iit/biomechanical-analysis-framework/tree/main/src/Logging/YarpImplementation) from the Logging since there is a version of it that does not use `YARP`? I already checked and it is not used anywhere.

CC @traversaro @GiulioRomualdi

**Comment by traversaro** [comment]
> Since we want to move away from `YARP`, does it make sense to remove the [`YarpImplementation`](https://github.com/ami-iit/biomechanical-analysis-framework/tree/main/src/Logging/YarpImplementation) from the Logging since there is a version of it that does not use `YARP`?

I guess the main point that we want to make sure is that BAF can be used without problems without YARP, but when used with YARP, it may be useful to have support to redirect the baf/spdlog output to YARP? Anyhow I do not have a strong opinion on this, if you prefer to remove it feel free to remove it.

**Comment by S-Dafarra** [comment]
I would also mention that I would like to start using BAF also in the teleoperation pipeline sooner or later. There I don't think we will move out of ``yarp`` any time soon.

**Comment by davidegorbani** [comment]
> I would also mention that I would like to start using BAF also in the teleoperation pipeline sooner or later. There I don't think we will move out of `yarp` any time soon.

You are right, I didn't consider it; I will close this issue as not planned then.
