### ISSUE TITLE
Add dynamics estimation algorithms

### ISSUE THREAD

**Issue by lrapetti** [ami-iit/biomechanical-analysis-framework#5]
- [ ] Berdy Algorithm
- [ ] SOT Berdy Algorithm

**Comment by davidegorbani** [comment]
I opened the branch [add_ID](https://github.com/ami-iit/biomechanical-analysis-framework/tree/add_ID) to address this issue.

**Comment by davidegorbani** [comment]
I created an application to test the code I wrote and used a dataset collected by @claudia-lat in which she was holding a weight of 5 kg. I compared the estimated wrenches computed with BAF with the ones computed with HDE and the comparison is shown in the following plot:

![estimatedWrenches](https://github.com/ami-iit/biomechanical-analysis-framework/assets/101326942/c5e9aeec-fa0f-43ea-bd87-ad4e9419827f)

As it is possible to notice, the forces of the feet are very similar unless for a small delay in BAF, while the forces of the hands present a small offset in the $x$ and $y$ directions. I have to investigate the reason for this offset further.

**Comment by davidegorbani** [comment]
I found that the differences in the feet forces were due to synchronization of the data while the difference in the hands forces were due to the wrong human mass that I set (62 kg instead of 61 kg); here is the comparison of the forces:


![estimatedWrenches2](https://github.com/ami-iit/biomechanical-analysis-framework/assets/101326942/4addd943-57f9-4a52-aa86-e967133ad8c6)

**Comment by davidegorbani** [comment]
I used the same dataset of the above comment and compared also the joint torques estimated with BAF and HDE and they match as it is possible to notice from the following figure:

![jointTorques](https://github.com/ami-iit/biomechanical-analysis-framework/assets/101326942/34098c65-1ffa-403e-84a0-2048e7865162)

**Comment by davidegorbani** [comment]
I used the same dataset as the previous comment to compare also the estimated joint torques and compare them with the ones calculated by HDE; both BAF and HDE give the same results as it is possible to notice from the following figure:
![jointTorques](https://github.com/ami-iit/biomechanical-analysis-framework/assets/101326942/337aa3c3-7156-4eaf-938b-66ce3fa4edbe)

**Comment by davidegorbani** [comment]
I opened #33 to merge the branch in master.
