### ISSUE TITLE
Add machinery for Python bindings generation

### ISSUE THREAD

**Issue by lrapetti** [ami-iit/biomechanical-analysis-framework#6]

**Comment by claudia-lat** [comment]
@davidegorbani what is the status of this activity?

**Comment by davidegorbani** [comment]
I haven't done it yet; for the moment it is not a high priority issue so I will work on it in the future.

**Comment by GiulioRomualdi** [comment]
Starting from next week we start implementing the bindings

**Comment by GiulioRomualdi** [comment]
First PR: https://github.com/ami-iit/biomechanical-analysis-framework/pull/48

**Comment by davidegorbani** [comment]
The bindings for the `HumanIK` class were added with #52, I will add the bindings for the dynamics with a new PR.

**Comment by davidegorbani** [comment]
Closing as the bindings for the class `HumanID` were added with #53.

**Comment by claudia-lat** [comment]
CC @LudovicaDanovaro
